version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: listify_postgres
    environment:
      POSTGRES_USER: listify_user
      POSTGRES_PASSWORD: listify_pass
      POSTGRES_DB: listify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listify_user -d listify_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: